### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by itemic** [dan-wong/engineering-textbooks#4]
There's no README file, which can make it difficult for your contributors to contribute to this.

**Comment by itemic** [comment]
@softeng-701

**Comment by dan-wong** [comment]
Please write the readme for me please

**Comment by mohan-cao** [comment]
Please format the issue in a user story style

**Comment by mohan-cao** [comment]
GIVEN that the user wants to see a README
WHEN the user navigates to the home page
THEN show the README

**Comment by dan-wong** [comment]
Sounds good, I'll assign you as well

**Comment by dan-wong** [comment]
wow I can't assign you mohan

**Comment by itemic** [comment]
Forgot to add the "closes #4" thing so i guess i'll just close it manually
